<h3>This new page is generated by CRM/Volunteer/Page/Listings.php</h3>

{foreach from=$sortedResults key=display_date item=assignments}
<h1>{$display_date}</h1>
<table>
    <tr>
        <th>Volunteer Name</th>
        <th>Role</th>
        <th>Contact</th>
    </tr>
    {foreach from=$assignments item=assignment}
    <tr>
        <td>{$assignment.name}</td>
        <td>{$assignment.role}</td>
        <td>{$assignment.email}</td>
    </tr>
    {/foreach}    
</table>
{/foreach}