<?xml version="1.0" encoding="iso-8859-1" ?>

<CustomData>
  <CustomGroups>
    <CustomGroup>
      <name>CiviVolunteer</name>
      <title>CiviVolunteer</title>
      <extends>Activity</extends>
      <extends_entity_column_value_option_group>activity_type</extends_entity_column_value_option_group>
      <extends_entity_column_value_option_value>Volunteer</extends_entity_column_value_option_value>
      <extends_entity_column_value>:;:;:;{$volunteer_activity_type_id}:;:;:;</extends_entity_column_value>
      <style>Inline</style>
      <collapse_display>1</collapse_display>
      <help_pre></help_pre>
      <help_post></help_post>
      <weight>2</weight>
      <is_active>1</is_active>
      <table_name>civicrm_value_civivolunteer_4</table_name>
      <is_multiple>0</is_multiple>
      <collapse_adv_display>0</collapse_adv_display>
      <created_date>0000-00-00 00:00:00</created_date>
      <is_reserved>1</is_reserved>
    </CustomGroup>
  </CustomGroups>
  <CustomFields>
    <CustomField>
      <name>Volunteer_Status</name>
      <label>Volunteer Status</label>
      <data_type>String</data_type>
      <html_type>Select</html_type>
      <is_required>0</is_required>
      <is_searchable>0</is_searchable>
      <is_search_range>0</is_search_range>
      <weight>1</weight>
      <is_active>1</is_active>
      <is_view>0</is_view>
      <text_length>255</text_length>
      <note_columns>60</note_columns>
      <note_rows>4</note_rows>
      <column_name>volunteer_status_7</column_name>
      <option_group_name>volunteer_status_20130617135236</option_group_name>
      <custom_group_name>CiviVolunteer</custom_group_name>
    </CustomField>
    <CustomField>
      <name>Time_Scheduled_In_minutes</name>
      <label>Time Scheduled - In minutes</label>
      <data_type>Int</data_type>
      <html_type>Text</html_type>
      <is_required>0</is_required>
      <is_searchable>0</is_searchable>
      <is_search_range>0</is_search_range>
      <weight>2</weight>
      <is_active>1</is_active>
      <is_view>0</is_view>
      <text_length>255</text_length>
      <note_columns>60</note_columns>
      <note_rows>4</note_rows>
      <column_name>time_scheduled_in_minutes_8</column_name>
      <custom_group_name>CiviVolunteer</custom_group_name>
    </CustomField>
    <CustomField>
      <name>time_completed_In_minutes</name>
      <label>time completed - In minutes</label>
      <data_type>Float</data_type>
      <html_type>Text</html_type>
      <is_required>0</is_required>
      <is_searchable>0</is_searchable>
      <is_search_range>0</is_search_range>
      <weight>3</weight>
      <is_active>1</is_active>
      <is_view>0</is_view>
      <text_length>255</text_length>
      <note_columns>60</note_columns>
      <note_rows>4</note_rows>
      <column_name>time_completed_in_minutes_9</column_name>
      <custom_group_name>CiviVolunteer</custom_group_name>
    </CustomField>
  </CustomFields>
  <OptionGroups>
    <OptionGroup>
      <name>volunteer_status_20130617135236</name>
      <title>Volunteer Status</title>
      <is_reserved>1</is_reserved>
      <is_active>1</is_active>
    </OptionGroup>
  </OptionGroups>
  <OptionValues>
    <OptionValue>
      <label>Available</label>
      <value>Available</value>
      <name>Available</name>
      <is_default>0</is_default>
      <weight>1</weight>
      <is_optgroup>0</is_optgroup>
      <is_reserved>0</is_reserved>
      <is_active>1</is_active>
      <option_group_name>volunteer_status_20130617135236</option_group_name>
    </OptionValue>
    <OptionValue>
      <label>Scheduled</label>
      <value>Scheduled</value>
      <name>Scheduled</name>
      <is_default>0</is_default>
      <weight>2</weight>
      <is_optgroup>0</is_optgroup>
      <is_reserved>0</is_reserved>
      <is_active>1</is_active>
      <option_group_name>volunteer_status_20130617135236</option_group_name>
    </OptionValue>
    <OptionValue>
      <label>Completed</label>
      <value>Completed</value>
      <name>Completed</name>
      <is_default>0</is_default>
      <weight>3</weight>
      <is_optgroup>0</is_optgroup>
      <is_reserved>0</is_reserved>
      <is_active>1</is_active>
      <option_group_name>volunteer_status_20130617135236</option_group_name>
    </OptionValue>
    <OptionValue>
      <label>Not used</label>
      <value>Not used</value>
      <name>Not_used</name>
      <is_default>0</is_default>
      <weight>4</weight>
      <is_optgroup>0</is_optgroup>
      <is_reserved>0</is_reserved>
      <is_active>1</is_active>
      <option_group_name>volunteer_status_20130617135236</option_group_name>
    </OptionValue>
    <OptionValue>
      <label>No-show</label>
      <value>No-show</value>
      <name>No_show</name>
      <is_default>0</is_default>
      <weight>5</weight>
      <is_optgroup>0</is_optgroup>
      <is_reserved>0</is_reserved>
      <is_active>1</is_active>
      <option_group_name>volunteer_status_20130617135236</option_group_name>
    </OptionValue>
  </OptionValues>
</CustomData>
