<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from org.civicrm.volunteer/xml/schema/CRM/Volunteer/ProjectContact.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:ad9c73366889463b89e80382d2fa0332)
 */
use CRM_Volunteer_ExtensionUtil as E;

/**
 * Database access object for the ProjectContact entity.
 */
class CRM_Volunteer_DAO_ProjectContact extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '4.5';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_volunteer_project_contact';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * @var int
   */
  public $id;

  /**
   * Foreign key to the Volunteer Project for this record
   *
   * @var int
   */
  public $project_id;

  /**
   * Foreign key to the Contact for this record
   *
   * @var int
   */
  public $contact_id;

  /**
   * Nature of the contact's relationship to the Volunteer Project (e.g., Beneficiary). See option group volunteer_project_relationship.
   *
   * @var int
   */
  public $relationship_type_id;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_volunteer_project_contact';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Volunteer Project Contacts') : E::ts('Volunteer Project Contact');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'project_id', 'civicrm_volunteer_project', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'contact_id', 'civicrm_contact', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('CiviVolunteer ProjectContact Row ID'),
          'required' => TRUE,
          'where' => 'civicrm_volunteer_project_contact.id',
          'table_name' => 'civicrm_volunteer_project_contact',
          'entity' => 'ProjectContact',
          'bao' => 'CRM_Volunteer_DAO_ProjectContact',
          'localizable' => 0,
          'readonly' => TRUE,
          'add' => '4.5',
        ],
        'project_id' => [
          'name' => 'project_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('CiviVolunteer Project ID'),
          'description' => E::ts('Foreign key to the Volunteer Project for this record'),
          'required' => TRUE,
          'where' => 'civicrm_volunteer_project_contact.project_id',
          'table_name' => 'civicrm_volunteer_project_contact',
          'entity' => 'ProjectContact',
          'bao' => 'CRM_Volunteer_DAO_ProjectContact',
          'localizable' => 0,
          'FKClassName' => 'CRM_Volunteer_DAO_Project',
          'add' => '4.5',
        ],
        'contact_id' => [
          'name' => 'contact_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Contact ID'),
          'description' => E::ts('Foreign key to the Contact for this record'),
          'required' => TRUE,
          'where' => 'civicrm_volunteer_project_contact.contact_id',
          'table_name' => 'civicrm_volunteer_project_contact',
          'entity' => 'ProjectContact',
          'bao' => 'CRM_Volunteer_DAO_ProjectContact',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Contact',
          'add' => '4.5',
        ],
        'relationship_type_id' => [
          'name' => 'relationship_type_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Relationship Type'),
          'description' => E::ts('Nature of the contact\'s relationship to the Volunteer Project (e.g., Beneficiary). See option group volunteer_project_relationship.'),
          'required' => TRUE,
          'where' => 'civicrm_volunteer_project_contact.relationship_type_id',
          'table_name' => 'civicrm_volunteer_project_contact',
          'entity' => 'ProjectContact',
          'bao' => 'CRM_Volunteer_DAO_ProjectContact',
          'localizable' => 0,
          'pseudoconstant' => [
            'optionGroupName' => 'volunteer_project_relationship',
            'optionEditPath' => 'civicrm/admin/options/volunteer_project_relationship',
          ],
          'add' => '4.5',
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'volunteer_project_contact', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'volunteer_project_contact', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
