<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2019
 *
 * Generated from C:\xampp\htdocs\civicrm-volunteer\sites\default\files\civicrm\ext\org.civicrm.volunteer\xml/schema/CRM/Volunteer/VolunteerAppeal.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:8c8faa3e1dfccd0b975372dc86e82ff0)
 */

/**
 * Database access object for the VolunteerAppeal entity.
 */
class CRM_Volunteer_DAO_VolunteerAppeal extends CRM_Core_DAO {

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_volunteer_appeal';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique VolunteerAppeal ID
   *
   * @var int unsigned
   */
  public $id;

  /**
   * FK to Contact
   *
   * @var int unsigned
   */
  public $contact_id;

  /**
   * Project Id
   *
   * @var int unsigned
   */
  public $project_id;

  /**
   * title
   *
   * @var string
   */
  public $title;

  /**
   * image url
   *
   * @var string
   */
  public $image;

  /**
   * appeal teaser
   *
   * @var text
   */
  public $appeal_teaser;

  /**
   * appeal description
   *
   * @var text
   */
  public $appeal_description;

  /**
   * location
   *
   * @var int
   */
  public $location;

  /**
   * location done anywhere
   *
   * @var tinyint
   */
  public $location_done_anywhere;

  /**
   * is appeal active
   *
   * @var tinyint
   */
  public $is_appeal_active;

  /**
   * active fromdate
   *
   * @var date
   */
  public $active_fromdate;

  /**
   * active todate
   *
   * @var date
   */
  public $active_todate;

  /**
   * display volunteer shift
   *
   * @var tinyint
   */
  public $display_volunteer_shift;

  /**
   * hide appeal volunteer button
   *
   * @var tinyint
   */
  public $hide_appeal_volunteer_button;

  /**
   * volunteer skill aought
   *
   * @var string
   */
  public $volunteer_skill_aought;

  /**
   * custom fields
   *
   * @var string
   */
  public $custom_fields;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_volunteer_appeal';
    parent::__construct();
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static ::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'contact_id', 'civicrm_contact', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'project_id', 'civicrm_volunteer_project', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Volunteer_ExtensionUtil::ts('Unique VolunteerAppeal ID'),
          'required' => TRUE,
          'table_name' => 'civicrm_volunteer_appeal',
          'entity' => 'VolunteerAppeal',
          'bao' => 'CRM_Volunteer_DAO_VolunteerAppeal',
          'localizable' => 0,
        ],
        'contact_id' => [
          'name' => 'contact_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Volunteer_ExtensionUtil::ts('FK to Contact'),
          'table_name' => 'civicrm_volunteer_appeal',
          'entity' => 'VolunteerAppeal',
          'bao' => 'CRM_Volunteer_DAO_VolunteerAppeal',
          'localizable' => 0,
        ],
        'project_id' => [
          'name' => 'project_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Volunteer_ExtensionUtil::ts('Project Id'),
          'table_name' => 'civicrm_volunteer_appeal',
          'entity' => 'VolunteerAppeal',
          'bao' => 'CRM_Volunteer_DAO_VolunteerAppeal',
          'localizable' => 0,
        ],
        'title' => [
          'name' => 'title',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => CRM_Volunteer_ExtensionUtil::ts('Title'),
          'description' => CRM_Volunteer_ExtensionUtil::ts('title'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'table_name' => 'civicrm_volunteer_appeal',
          'entity' => 'VolunteerAppeal',
          'bao' => 'CRM_Volunteer_DAO_VolunteerAppeal',
          'localizable' => 0,
        ],
        'image' => [
          'name' => 'image',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => CRM_Volunteer_ExtensionUtil::ts('Image'),
          'description' => CRM_Volunteer_ExtensionUtil::ts('image url'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'table_name' => 'civicrm_volunteer_appeal',
          'entity' => 'VolunteerAppeal',
          'bao' => 'CRM_Volunteer_DAO_VolunteerAppeal',
          'localizable' => 0,
        ],
        'appeal_teaser' => [
          'name' => 'appeal_teaser',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => CRM_Volunteer_ExtensionUtil::ts('Appeal Teaser'),
          'description' => CRM_Volunteer_ExtensionUtil::ts('appeal teaser'),
          'table_name' => 'civicrm_volunteer_appeal',
          'entity' => 'VolunteerAppeal',
          'bao' => 'CRM_Volunteer_DAO_VolunteerAppeal',
          'localizable' => 0,
        ],
        'appeal_description' => [
          'name' => 'appeal_description',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => CRM_Volunteer_ExtensionUtil::ts('Appeal Description'),
          'description' => CRM_Volunteer_ExtensionUtil::ts('appeal description'),
          'table_name' => 'civicrm_volunteer_appeal',
          'entity' => 'VolunteerAppeal',
          'bao' => 'CRM_Volunteer_DAO_VolunteerAppeal',
          'localizable' => 0,
        ],
        'location' => [
          'name' => 'location',
          'type' => CRM_Utils_Type::T_INT,
          'title' => CRM_Volunteer_ExtensionUtil::ts('Location'),
          'description' => CRM_Volunteer_ExtensionUtil::ts('location'),
          'table_name' => 'civicrm_volunteer_appeal',
          'entity' => 'VolunteerAppeal',
          'bao' => 'CRM_Volunteer_DAO_VolunteerAppeal',
          'localizable' => 0,
        ],
        'location_done_anywhere' => [
          'name' => 'location_done_anywhere',
          'type' => CRM_Utils_Type::T_INT,
          'title' => CRM_Volunteer_ExtensionUtil::ts('Location Done Anywhere'),
          'description' => CRM_Volunteer_ExtensionUtil::ts('location done anywhere'),
          'table_name' => 'civicrm_volunteer_appeal',
          'entity' => 'VolunteerAppeal',
          'bao' => 'CRM_Volunteer_DAO_VolunteerAppeal',
          'localizable' => 0,
        ],
        'is_appeal_active' => [
          'name' => 'is_appeal_active',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Volunteer_ExtensionUtil::ts('is appeal active'),
          'table_name' => 'civicrm_volunteer_appeal',
          'entity' => 'VolunteerAppeal',
          'bao' => 'CRM_Volunteer_DAO_VolunteerAppeal',
          'localizable' => 0,
        ],
        'active_fromdate' => [
          'name' => 'active_fromdate',
          'type' => CRM_Utils_Type::T_DATE,
          'title' => CRM_Volunteer_ExtensionUtil::ts('Active Fromdate'),
          'description' => CRM_Volunteer_ExtensionUtil::ts('active fromdate'),
          'table_name' => 'civicrm_volunteer_appeal',
          'entity' => 'VolunteerAppeal',
          'bao' => 'CRM_Volunteer_DAO_VolunteerAppeal',
          'localizable' => 0,
        ],
        'active_todate' => [
          'name' => 'active_todate',
          'type' => CRM_Utils_Type::T_DATE,
          'title' => CRM_Volunteer_ExtensionUtil::ts('Active Todate'),
          'description' => CRM_Volunteer_ExtensionUtil::ts('active todate'),
          'table_name' => 'civicrm_volunteer_appeal',
          'entity' => 'VolunteerAppeal',
          'bao' => 'CRM_Volunteer_DAO_VolunteerAppeal',
          'localizable' => 0,
        ],
        'display_volunteer_shift' => [
          'name' => 'display_volunteer_shift',
          'type' => CRM_Utils_Type::T_INT,
          'title' => CRM_Volunteer_ExtensionUtil::ts('Display Volunteer Shift'),
          'description' => CRM_Volunteer_ExtensionUtil::ts('display volunteer shift'),
          'table_name' => 'civicrm_volunteer_appeal',
          'entity' => 'VolunteerAppeal',
          'bao' => 'CRM_Volunteer_DAO_VolunteerAppeal',
          'localizable' => 0,
        ],
        'hide_appeal_volunteer_button' => [
          'name' => 'hide_appeal_volunteer_button',
          'type' => CRM_Utils_Type::T_INT,
          'title' => CRM_Volunteer_ExtensionUtil::ts('Hide Appeal Volunteer Button'),
          'description' => CRM_Volunteer_ExtensionUtil::ts('hide appeal volunteer button'),
          'table_name' => 'civicrm_volunteer_appeal',
          'entity' => 'VolunteerAppeal',
          'bao' => 'CRM_Volunteer_DAO_VolunteerAppeal',
          'localizable' => 0,
        ],
        'volunteer_skill_aought' => [
          'name' => 'volunteer_skill_aought',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => CRM_Volunteer_ExtensionUtil::ts('Volunteer Skill Aought'),
          'description' => CRM_Volunteer_ExtensionUtil::ts('volunteer skill aought'),
          'maxlength' => 500,
          'size' => CRM_Utils_Type::HUGE,
          'table_name' => 'civicrm_volunteer_appeal',
          'entity' => 'VolunteerAppeal',
          'bao' => 'CRM_Volunteer_DAO_VolunteerAppeal',
          'localizable' => 0,
        ],
        'custom_fields' => [
          'name' => 'custom_fields',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => CRM_Volunteer_ExtensionUtil::ts('Custom Fields'),
          'description' => CRM_Volunteer_ExtensionUtil::ts('custom fields'),
          'maxlength' => 500,
          'size' => CRM_Utils_Type::HUGE,
          'table_name' => 'civicrm_volunteer_appeal',
          'entity' => 'VolunteerAppeal',
          'bao' => 'CRM_Volunteer_DAO_VolunteerAppeal',
          'localizable' => 0,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'volunteer_appeal', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'volunteer_appeal', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
